package setanalyzer;

public enum Token {
     ERROR, DEFINICION, CONJUNTO_UNIVERSO, LLAVE_ABIERTA, LLAVE_CERRADA,  
     COMA, IGUAL, ELEMENTO, SPACES, CONJUNTO, OPERACION, PARENTESIS_ABIERTO,
     PARENTESIS_CERRADO, UNION, INTERSECCION, DIFERENCIA, PRODUCTO_CRUZ, COMPLEMENTO
}
    